"""Add status and summary to ResearchPaper

Revision ID: 273110cb84c7
Revises: 5b6421e47069
Create Date: 2026-07-07 11:42:56.196811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273110cb84c7'
down_revision: Union[str, Sequence[str], None] = '5b6421e47069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_papers', sa.Column('status', sa.String(), nullable=True))
    op.add_column('research_papers', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_papers', 'summary')
    op.drop_column('research_papers', 'status')
    # ### end Alembic commands ###
